#!/bin/sh
set -e

# If the package is removed, purged or installation is aborted, try to
# remove the default mountpoints.
#
# Failure to do so is not considered fatal, because they may be in use by
# the system administrator or some other daemon on the system.
if [ "$1" = remove -o "$1" = abort-install -o "$1" = purge ]; then
	rm -f /media/usb 2> /dev/null || :
	n=0
	while [ $n -le 9 ]; do
		rmdir /media/usb$n 2> /dev/null || :
		n=$(( n + 1 ))
	done
fi

#DEBHELPER#

exit 0
