#!/bin/sh
set -e

# If the package is installed, try to create the default mountpoints.
# Failure to do so is not considered fatal.
if [ "$1" = install ]; then
	mkdir -p /media/usb0 2> /dev/null || :
	ln -s usb0 /media/usb 2> /dev/null || :
fi

#DEBHELPER#

exit 0
