#!/bin/sh
# This script creates the label name symlink in /var/run/usbmount.
#
set -e

# Load shared functions
. /usr/share/usbmount/functions

# Replace spaces with underscores, remove special characters in label
# name.
UM_LABEL="$( echo "$UM_LABEL" | sed 's/ /_/g; s/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ._-]//g' )"

# Exit if label name are empty.
[ -n "$UM_LABEL" ] || exit 0

# Build symlink name.
name="$UM_LABEL"

# If the symlink does not yet exist, create it.
if [ -e "/var/run/usbmount/$name" ]; then
	log debug "$UM_DEVICE (hook) symlink $name already exist"
else
	ln -sf "$UM_MOUNTPOINT" "/var/run/usbmount/$name" &&
		log debug "$UM_DEVICE (hook) symlink $name created"
fi

exit 0

# vim: noet
