#!/bin/sh
# This script removes symlinks that do not target a used mountpoint in
# /var/run/usbmount.
# Copyright (C) 2005 Martin Dickopp
#
# This file is free software; the copyright holder gives unlimited
# permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
set -e

# Load shared functions
. /usr/share/usbmount/functions

find /var/run/usbmount/ -type l -printf '%p;%l\n' | while read -r name; do
	link_name="${name%;*}"
	link_basename="${link_name##*/}"
	link_target="${name#*;}"

	# Check if the target of the symlink is used as mountpoint by a device
	mount_source="$( findmnt --noheadings --output SOURCE --mountpoint "$link_target" || : )"
	if [ -z "$mount_source" ]; then
		rm "$link_name" &&
			log debug "$UM_DEVICE (hook) symlink $link_basename removed"
	else
		log debug "$UM_DEVICE (hook) symlink $link_basename is used by $link_target"
	fi
done

exit 0

# vim: noet
